---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /host/projects/aclab-middlewares/.volumes-k8s/postgresql
    type: DirectoryOrCreate
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: valkey-queue-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /host/projects/aclab-middlewares/.volumes-k8s/valkey-queue
    type: DirectoryOrCreate
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-01-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /host/projects/aclab-middlewares/.volumes-k8s/neo4j-01
    type: DirectoryOrCreate
  storageClassName: local-path
